### ISSUE TITLE
Firebase Download and Upload

### ISSUE THREAD

**Issue by HisaamH** [Sathyasrip/277--Android-TeamProject#3]
Firebase Google Cloud store will be used (as it is the easiest) to safely store the Review versions which will be uploaded to a folder labeled either UUID_username, UUID_ReviewNameWithoutSpaces or even username_ReviewNameWithoutSpaces. Inside each of these folders will be versions listed as filename_VersionNumber.pdf. The filename is the original filename with an appended VersionNumber (ex. Version1 or Version10) to it, which is tracked via the Firebase NoSQL database. (If local, use a local SQL database to store the different versions).

Currently only picking a file seems to work with uploading to firebase giving issues. S can update her changes here.

**Comment by Sathyasrip** [comment]
Uploading a file firebase storage fixed

**Comment by HisaamH** [comment]
This issue can be closes. The Upload and Download portion has already been implemented in this app with the latest check-in. All that needs to be done now, is to just pull existing entries of Reviews from the database and work on the final activity: StartReview, to add comments to a PDF and save highlights.
